### ISSUE TITLE
Processos para iniciar uma tradução

### ISSUE THREAD

**Issue by Marlysson** [entrylvl/traducoes-de-artigos#10]
Olá, muito show a iniciativa do projeto de tradução.

Mas surgiu uma dúvida, após selecionar o artigo para tradução vocês falam com o autor original com relação a permissão ? Ou só escolhem, traduzem e postam...

**Comment by anardy** [comment]
Eu também achei muito interessante esta iniciativa.

O mais correto seria entrar em contato com o autor original e solicitar a permissão para realizar a tradução.

**Comment by CarolPC** [comment]
Todos os artigos que já estão traduzidos nós entramos em contato com o autor. Esse que está em andamento https://github.com/entrylvl/traducoes-de-artigos/pull/11 acredito que não foi feito, porque depois de sugerido na issue, o PR foi logo criado. Vou tentar entrar em contato com eles e aviso aqui quando tiver a resposta.
