### ISSUE TITLE
Traduções de Cursos

### ISSUE THREAD

**Issue by edkf** [entrylvl/traducoes-de-artigos#12]
Olá!
Adorei a ideia do projeto e também gostaria de contribuir.
Teve um desafio do @wesbos, o [Javascript30](https://javascript30.com/) que me ajudou muito a entender como o javascript funciona, e acredito que se o curso tivesse legendas em pt_br ajudaria muitas outras pessoas também.
O que acham de trabalharmos também com traduções de cursos?

**Comment by juliofortunato** [comment]
Bem interessante essa ideia, o Javascript30 também me ajudou muito! 
Mas creio que, como o projeto está engatinhando ainda, o ideal seria focarmos primeiramente em consolidar nosso conteúdo em artigos para então passarmos a expandir para outras "mídias".

**Comment by edkf** [comment]
Faz total sentido @JulioFortunato.
Vou ficar de olho no repositório e sempre que encontrar algum artigo interessante vou sugerir aqui.
Abraços =)
