### ISSUE TITLE
Imagem do Artigo: A promessa de uma festa do hambúrguer

### ISSUE THREAD

**Issue by anardy** [entrylvl/traducoes-de-artigos#13]
Na [imagem](https://camo.githubusercontent.com/6d68ee39e6c3fbde44fe011abec7efa4bb636286/68747470733a2f2f692e696d6775722e636f6d2f744e704e6a6e422e706e67), ficou faltando a tradução da função _order_ para **pedido**.

**Comment by CaiqueMitsuoka** [comment]
Essa é minha, valeu !

**Comment by juliofortunato** [comment]
@CaiqueMitsuoka Aproveitando, em `A bandeja da promise as veses está vazia`, deveria ser "A bandeja da promise **às vezes** está vazia"
