### ISSUE TITLE
But why can't I code like that?

### ISSUE THREAD

**Issue by feliperli** [entrylvl/traducoes-de-artigos#15]
Estava lendo o blog da Mariko e me deparei com este artigo: 
https://kosamari.com/notes/but-why-cant-i-code-like-that

Ele é relativamente curto e achei bem interessante. O que acham?

**Comment by CarolPC** [comment]
Boa ideia, @feliperli. Única coisa é que já temos 2 artigos dela traduzidos, talvez pudéssemos variar um pouco os autores.

**Comment by felipebernardes** [comment]
@feliperli concordo com a @CarolPC . Eu vou fechar essa issue por enquanto.
