### ISSUE TITLE
Sugestão: Hacktoberfest

### ISSUE THREAD

**Issue by phillipnunes** [entrylvl/traducoes-de-artigos#16]
O que acham de adequarmos esse repositório ao Hacktoberfest?
Link: https://hacktoberfest.digitalocean.com/

Seria inclusive uma oportunidade para darmos uma organizada no fluxo de trabalho, criar padrões e etc para o repositório.

**Comment by phillipnunes** [comment]
Não sei se a galera que vai falar sobre git/comitão no sábado na FATEC-SO ta sabendo desse evento, mas acredito que citar isso lá seria um incentivo a mais pro pessoal participar.

Não conheço a galera que vai palestrar.

**Comment by CaiqueMitsuoka** [comment]
Eu sou um dos organizadores, vou puxar isso la sim ! Cola lá.

**Comment by CarolPC** [comment]
Além de melhorar o README, também já criei a label para o `Hacktoberfest`
