### ISSUE TITLE
DevTranslate - Projeto Semelhante de Tradução

### ISSUE THREAD

**Issue by Lucasktrindade** [entrylvl/traducoes-de-artigos#17]
Fala galera,
Li o artigo de vocês na BrazilJS e acho bem bacana essa idéia, tem um projeto semelhante ao de vocês que está sendo tocado tem um tempo, acho que vocês poderiam unir forças.

Valeu, segue link do projeto abaixo.

https://github.com/devtranslate

**Comment by felipebernardes** [comment]
Oi @Lucasktrindade , tudo bem?

traduções são apenas parte da proposta do entrylvl. por isso, acho que não vale a pena juntar as panelas.

mesmo assim, obrigado pela sugestão! :)
