### ISSUE TITLE
Is vanilla js worth learning?

### ISSUE THREAD

**Issue by cbsorrilha** [entrylvl/traducoes-de-artigos#19]
Sugiro traduzirmos esse aqui.

https://medium.freecodecamp.org/is-vanilla-javascript-worth-learning-absolutely-c2c67140ac34

É uma coisa de que a galera de entry lvl faria bom proveito.

**Comment by CarolPC** [comment]
Boa sugestão! Acabei de enviar um tweet para o autor perguntando se podemos traduzir.

**Comment by cbsorrilha** [comment]
Nice \o
Assim que tivermos a resposta, eu posso pegar essa primeira sessão, de introdução.

**Comment by CarolPC** [comment]
<img width="625" alt="screen shot 2017-10-02 at 17 08 21" src="https://user-images.githubusercontent.com/7128885/31097040-59fd7676-a794-11e7-804a-e6f069183512.png">

Aceito!

**Comment by cbsorrilha** [comment]
Ótimo, vou pegar a introdução, então.

**Comment by marinalimeira** [comment]
@cbsorrilha posso ajudar? :)

**Comment by cbsorrilha** [comment]
Claro! :D 
Eu criei a branch e criei o arquivo onde a tradução vai ficar. Eu pensei em dividir os segmentos pelos sub-títulos.
O que acha?
@marinalimeira

**Comment by marinalimeira** [comment]
@cbsorrilha perfeito! Já me adiantei e até `…but investing time in Vanilla JavaScript will pay off in the long run` tá pronto :P

**Comment by marinalimeira** [comment]
- [X] Is Vanilla JavaScript worth learning? Absolutely.
- [X] Everybody wants developers with knowledge of ${addTheHotFramework}…
- [X] …but investing time in Vanilla JavaScript will pay off in the long run
- [X] Personal experience
- [X] Give me something I can learn from
- [ ] Learn Vanilla JavaScript, now

https://github.com/entrylvl/traducoes-de-artigos/compare/master...marinalimeira:i18n-is-vanilla-js-worth-learning
cc @cbsorrilha

**Comment by cbsorrilha** [comment]
@marinalimeira 
Pronto, eu peguei o ultimo paragrafo e dei uma revisada no seu texto.  Tá excelente! 👌 
Se você e mais alguém quiser re-revisar antes de eu fazer a PR, fique à vontade.
