### ISSUE TITLE
Handling an ajax response in javascript with or without jquery

### ISSUE THREAD

**Issue by Jhoow13** [entrylvl/traducoes-de-artigos#23]
Olá pessoal,

Há algum tempo atrás fiz um projeto que uso um ajax bem simples e esse artigo me ajudou bastante, gostaria de indica-lo para tradução.

https://www.mattlunn.me.uk/blog/2011/11/handling-an-ajax-response-in-javascript-with-or-without-jquery/ 

valeu !

**Comment by matheus208** [comment]
Posso traduzir hoje à noite :)

**Comment by matheus208** [comment]
Opa desculpa, não consegui fazer ontem, mas terminei hoje: https://github.com/entrylvl/traducoes-de-artigos/pull/24
