### ISSUE TITLE
Adição de label

### ISSUE THREAD

**Issue by phillipnunes** [entrylvl/traducoes-de-artigos#26]
No arquivo de contribuição cita esse passo:
"Ao terminar a tradução do artigo, adicione a label pronto para revisão e marque pessoas para ajudarem na revisão."

Qualquer contribuidor desse rep consegue associar labels os PRs? Tentei agora no PR #11 mas não consegui.

**Comment by CarolPC** [comment]
Acabei de adicionar a tag `pronto para revisão` no PR!
