### ISSUE TITLE
Colocar as imagens neste respositório

### ISSUE THREAD

**Issue by CaiqueMitsuoka** [entrylvl/traducoes-de-artigos#28]
Atualmente as imagens dos antigos estão sendo hosteadas no imgur, @vitortalaia deu a ideia de colocarmos aqui mesmo.

Minha proposta: `imagens/:nome-do-md-do-artigo/:numero-em-ordem-de-aparição`
Para ficar facil a rastreabilidade em caso de correções e não ficar tudo misturado em uma pasta só.
Imagens que não foram traduzidas, só utilizaremos os links originais.

ex:
```
imagens/como-ser-um-compilador--faca-um-compilador-com-javascript/1.png
imagens/como-ser-um-compilador--faca-um-compilador-com-javascript/2.png
```

**Comment by juliofortunato** [comment]
Acho uma ótima ideia!

**Comment by vitortalaia** [comment]
Uma outra ideia, poderia ser colocar os artigos que possuem imagens em diretórios. Ex:

```
- javascript/
  -- como-ser-um-compilador/
    -- artigo.md
    -- imagens/
      -- 1.png
      -- 2.png
```

**Comment by CaiqueMitsuoka** [comment]
Eu acho que colocar os `md`s atrás de mais uma camada de pasta ruim, clicar na linguagem e ja ter acesso a todos os artigos é uma feature bem bacana do ponto de vista de um leitor.

Ex:
```
(Lista de linguagens) -> clique na linguagem -> (lista de artigos) -> clique no nome do artigo -> clique no .md -> não parece interessante -> volta -> volta -> (lista de artigos)
```

```
(Lista de linguagens) -> clique na linguagem -> (lista de artigos) -> clique no nome do artigo -> não parece interessante -> volta -> (lista de artigos)
```

Além de que não existe necessidade da imagem ser acessada separadamente pelo leitor. Uma vez que todas elas estão nos artigos necessáriamente, e ele pode clicar na própria imagem para ir até ela.

**Comment by vitortalaia** [comment]
@CaiqueMitsuoka Não vejo problema em colocar num diretório, temos a listagem dos artigos no README para serem acessadas.

**Comment by felipebernardes** [comment]
+1 pro @vitortalaia , gostei da estrutura proposta. já vi repos grandes fazendo isso tb.
