### ISSUE TITLE
Canal de comunicação

### ISSUE THREAD

**Issue by willamesoares** [entrylvl/traducoes-de-artigos#30]
Galera, o que vocês acham de criar um canal pra facilitar a comunicação, pedir review, sugestões de tradução e tal?

Talvez um chat no Slack ou qualquer outra ferramenta do tipo.

**Comment by vitortalaia** [comment]
Eu acho uma ótima ideia

cc @entrylvl/entrylvl

**Comment by feliperli** [comment]
Também apoio

**Comment by cbsorrilha** [comment]
:+1:

**Comment by felipebernardes** [comment]
eu acho que como conversamos mais assincronamente do que qualquer outra coisa, talvez o gh issues funcione melhor que slack.
já estamos fazendo tudo isso por aqui e está funcionando bem, não acham?

**Comment by felipebernardes** [comment]
@CarolPC  @CaiqueMitsuoka o que vocês acham?

**Comment by CarolPC** [comment]
@felipebernardes não estou vendo problemas de comunicação ainda. Acho que podemos ficar só por aqui.

**Comment by felipebernardes** [comment]
Estou fechando essa issue por enquanto. Se acharem que vale a pena um slack num outro momento, por favor reabram a issue.
