### ISSUE TITLE
Local para divulgar os artigos traduzidos

### ISSUE THREAD

**Issue by woliveiras** [entrylvl/traducoes-de-artigos#36]
Olá, pessoal!

Temos uma comunidade (bem ativa) de pessoas em início de carreira precisando de artigos para acompanhar.

Criamos uma publicação no Medium que recebe qualquer artigo com assuntos interessantes para pessoas iniciantes.

Recentemente iniciamos uma verdadeira força tarefa para procurar pessoas para gerar conteúdo para a nossa comunidade, vide esses artigos:

* [O Training Center busca pessoas para criação de tutoriais](https://medium.com/trainingcenter/o-training-center-busca-pessoas-para-cria%C3%A7%C3%A3o-de-tutoriais-bb6587018276)
* [Qualquer pessoa pode escrever, pedir ou mandar um artigo no blog do Training Center](https://medium.com/trainingcenter/qualquer-pessoa-pode-escrever-pedir-ou-mandar-um-artigo-no-blog-do-training-center-fde2979e8067)

Nossa comunidade é totalmente aberta, com conteúdo e projetos gratuitos para ajudar as pessoas em início de carreira ou que buscam crescimento profissional (e sempre será): https://github.com/training-center/sobre.

Não queremos agregar conteúdo para que seja algo como uma marca de empresa que tem diversos artigos lá, queremos trazer conteúdo de qualidade para as pessoas da nossa comunidade (e de outras) e para isso ajudamos quem deseja escrever seus primeiros artigos e também fazemos uma [revisão](https://medium.com/trainingcenter/guia-de-editores-as-da-publicação-no-medium-do-training-center-d88aabf57cb2) focada na qualidade do artigo e usamos o Medium como plataforma para que quem escreveu tenha a liberdade de tirar esse artigo de dentro da publicação a qualquer momento. O artigo é da pessoa e está listado no Training Center somente para facilitar o nosso trabalho de divulgação desse conteúdo (já divulgamos diversos outros canais de conteúdo também). 

Gostaria de deixar aqui em aberto um pedido para quem quiser contribuir conosco enviando seus artigos traduzidos que tiverem conteúdo para iniciantes ou que seja voltado para carreira. Até se tiver como listar isso como opção no repositório (tipo: você pode compartilhar seu artigo com o Training Center).

Enfim, **parabéns pela iniciativa valorosa para a comunidade de desenvolvimento de software no Brasil**!

**Comment by felipebernardes** [comment]
Fala @woliveiras ! tudo bem?

Pelo que eu entendi, o **Training Center tem uma proposta parecida com a do entrylvl**: criar conteúdo direcionado a iniciantes/ingressantes na área de tecnologia.

Nós também temos um blog, que está sendo implementado, e todas as nossas traduções ficarão lá - temos um parser bem legal markdown pra html. Assim, depois que o blog estiver publicado, todas as traduções daqui aparecerão lá.

Dito isso, não temos interesse em juntar os projetos (pois acreditamos que diversidade é bom). Mas as traduções aqui feitas são open source.

Então, se você tiver interesse, pode copiar as traduções daqui e postar no Training Center, sem problemas!

Só pedimos que por favor inclua créditos (com link pro github) pro autor da tradução e pro post/markdown da tradução aqui no entrylvl.

Denovo, obrigado pelo convite!

**Comment by woliveiras** [comment]
Aaaaaa, perfeito, @felipebernardes!

Como comentei: de qualquer jeito vou ficar de olho pra divulgar nas nossas redes sociais e tentar trazer mais gente pra ajudar aqui, pois o projeto é muito útil! \o/

Valeu, cara.
