### ISSUE TITLE
Permissão

### ISSUE THREAD

**Issue by larismourullo** [entrylvl/traducoes-de-artigos#38]
Olá, eu possuo um projeto de tradução e organização de conteúdo traduzido de tecnologia chamado devtranslate aqui no github e gostaria de saber se vocês permitiriam colocar os artigos traduzidos de vocês lá pra galera vir aqui acessar :)

**Nosso site:** https://devtranslate.github.io/

**Comment by juliofortunato** [comment]
Oi @larismourullo, tudo bem?

As traduções feitas aqui são _open source_, então pode usá-las sim, sem problemas. ☺️ 

Só pedimos que por favor inclua créditos (com link pro github) pro autor da tradução e pro post/markdown da tradução aqui no entrylvl.

**Comment by larismourullo** [comment]
@JulioFortunato basicamente fazemos o redirecionamento para o projeto original no site informando sempre o autor original do artigo e o da tradução. Atualmente somos apenas uma fonte de artigos traduzidos, pretendemos expandir para tradução também, o bom de conhecer o projeto é que podemos parear para evitar traduções repetidas, e assim ter mais conteúdo traduzido e bem mais rápido 👍

**Comment by juliofortunato** [comment]
@larismourullo Perfeito!
