### ISSUE TITLE
Sugestão: Seção em inglês no README

### ISSUE THREAD

**Issue by amandavilela** [entrylvl/traducoes-de-artigos#40]
Pessoal, estava mandando mensagem para a Joanna Ngai do artigo de UX e coloquei o link do repo pra ela ver, mas me dei conta de que ela não entenderá muito do que temos por aqui... xD

O que vocês acham de: no README.md criar uma seção em inglês apenas explicando o que é esse repo para que os estrangeiros entendam do que se trata?

**Comment by ghost** [comment]
acho que seria top

**Comment by felipebernardes** [comment]
Muito bem observado @amandavilela ! você pode traduzir o README atual?

**Comment by amandavilela** [comment]
Traduzo sim :)

**Comment by amandavilela** [comment]
Traduzido no PR #45 ;)

**Comment by felipebernardes** [comment]
Valeu @amandavilela !
