### ISSUE TITLE
How I start: Elixir - José Valim

### ISSUE THREAD

**Issue by CaiqueMitsuoka** [entrylvl/traducoes-de-artigos#43]
Sugestão de tradução do artigo do How I start de Elixir, escrito pelo próprio @josevalim (Criador da linguagem). [link](http://howistart.org/posts/elixir/1/)

O artigo descreve uma implementação da mecânica de portais do jogo Portal de maneira rudimentar, porem passando pelas mecânicas do Elixir e de programação funcional.

O artigo ensina, de forma simples e rápida, a criar um novo projeto, pattern matching, gerenciamento de estado e nós distribuidos.

Me responsabilizo pelo contato com o autor e tradução do artigo completo.

**Comment by felipebernardes** [comment]
faz pls, mto bom
