### ISSUE TITLE
Dúvida: quais artigos traduzir?

### ISSUE THREAD

**Issue by notnotgabriel** [entrylvl/traducoes-de-artigos#7]
Ouvi a @CarolPC falando sobre o projeto no DNE, e pirei pois gosto muito de colaborar com traduções.
Existe uma lista com artigos que vocês querem traduzir?
Me disponho a ajudar.

**Comment by felipesoares6** [comment]
Eai @gabriel-ribeiro-ir  ainda não temos uma lista definida, mas podemos definir! Já tem algum artigo em mente? Conforme tivermos artigos definidos podemos criar alguma issue com isso, o que acha?

**Comment by CarolPC** [comment]
O que acham de traduzirmos os artigos de git da Atlassian? https://www.atlassian.com/git/tutorials/what-is-version-control podemos começar por esse.
@gabriel-ribeiro-ir @feliperli @JulioFortunato @CaiqueMitsuoka @felipesoares6 @vitortalaia

**Comment by notnotgabriel** [comment]
Por enquanto não tenho nenhum @felipesoares6. Mas assim que surgir eu já abro o PR.
