### ISSUE TITLE
Sugestão de artigo sobre Git

### ISSUE THREAD

**Issue by CarolPC** [entrylvl/traducoes-de-artigos#9]
O que acham de traduzirmos os artigos de git da Atlassian? https://www.atlassian.com/git/tutorials/what-is-version-control podemos começar por esse.
@gabriel-ribeiro-ir @feliperli @JulioFortunato @CaiqueMitsuoka @felipesoares6 @vitortalaia

**Comment by vitortalaia** [comment]
Acho show

**Comment by feliperli** [comment]
Vai ser ótimo, bora

**Comment by phillipnunes** [comment]
Como vcs tem feito? Uma pessoa pega e traduz inteiro? Ou se organizam pra cada um pegar uma parte?

**Comment by CarolPC** [comment]
Então, quem começa abre um PR e faz um comentário lá avisando qual seção está traduzindo e assim que terminar essa seção faz um commit. Se ela continuar pegando outras seções é só avisar no PR.

**Comment by phillipnunes** [comment]
Tá la o PR   :)

**Comment by notnotgabriel** [comment]
Tope! Ajudarei na tradução sim.

**Comment by notnotgabriel** [comment]
Fiquei na dúvida de como contribuir na tradução do artigo. Já que o PR #11 que o @phillipnunes criou é da master do fork dele direto para a master deste repo aqui.
